image: "docker/compose:1.28.5"

services:
  - docker:dind

variables:
  SHARED_PATH: /root/$CI_PROJECT_PATH

before_script:
  - docker info
  - docker-compose --version

stages:
  - build
  - test

build:
  stage: build
  script:
    - 'export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"'
    - echo ${SHARED_PATH}
    - mkdir -p ${SHARED_PATH}
    - cp -r ./* ${SHARED_PATH}
    - ls ${SHARED_PATH}
    - cd docker/build
    - docker-compose -f docker-compose-ci.yml up

test:
  stage: test
  before_script:
    - cd docker/user
    - docker-compose down
    - cd ../owner
    - docker-compose down
    - cd ../database
    - docker-compose down
    - cd ../..
  script:
    - mkdir -p $PWD/release/bin
    - cp $HOME/.m2/repository/com/hufudb/onedb/owner-postgresql/0.1-SNAPSHOT/owner-postgresql-0.1-SNAPSHOT-jar-with-dependencies.jar $PWD/release/bin/onedb_postgresql_owner.jar
    - cp $HOME/.m2/repository/com/hufudb/onedb/user-client/0.1-SNAPSHOT/user-client-0.1-SNAPSHOT-jar-with-dependencies.jar $PWD/release/bin/onedb_user_client.jar
    - cd docker/database
    - docker-compose up -d
    - sleep 5
    - cd ../owner
    - cp -r ../cert/ci cert
    - docker-compose up -d
    - cd ../test
    - docker-compose up
  after_script:
    - cd docker/test
    - docker-compose down
    - cd ../owner
    - docker-compose down
    - cd ../database
    - docker-compose down