version: '3.3'

services:
  owner1:
    image: maven:3.8-openjdk-11
    container_name: owner1
    working_dir: /root/onedb
    restart: "no"
    command: nohup java -jar ./bin/onedb_postgresql_owner.jar -c ./config/server1.json > ./log/owner1.log &
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    networks:
      - database_owner_net_1
      - public_net
    ports:
      - 12345:12345

  owner2:
    image: maven:3.8-openjdk-11
    container_name: owner2
    working_dir: /root/onedb
    restart: "no"
    command: nohup java -jar ./bin/onedb_postgresql_owner.jar -c ./config/server2.json > ./log/owner2.log &
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    networks:
      - database_owner_net_2
      - public_net
    ports:
      - 12346:12345

  owner3:
    image: maven:3.8-openjdk-11
    container_name: owner3
    working_dir: /root/onedb
    restart: "no"
    command: nohup java -jar ./bin/onedb_postgresql_owner.jar -c ./config/server3.json > ./log/owner3.log &
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    networks:
      - database_owner_net_3
      - public_net
    ports:
      - 12347:12345

networks:
  database_owner_net_1:
    external: true
  database_owner_net_2:
    external: true
  database_owner_net_3:
    external: true
  public_net:
    driver: bridge