version: '3.3'

services:
  owner_1:
    image: maven:3.8-openjdk-11
    container_name: owner_1
    working_dir: /root/onedb
    restart: "no"
    command: nohup java -jar ./bin/onedb_server.jar -c ./config/server1.json > ./log/owner1.log &
    links:
      - "postgres_1:db"
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    depends_on:
      - "postgres_1"

  owner_2:
    image: maven:3.8-openjdk-11
    container_name: owner_2
    working_dir: /root/onedb
    restart: "no"
    command: nohup java -jar ./bin/onedb_server.jar -c ./config/server2.json > ./log/owner2.log &
    links:
      - "postgres_2:db"
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    depends_on:
      - "postgres_1"

  owner_3:
    image: maven:3.8-openjdk-11
    container_name: owner_3
    working_dir: /root/onedb
    links:
      - "postgres_3:db"
    restart: "no"
    command: nohup java -jar ./bin/onedb_server.jar -c ./config/server3.json > ./log/owner3.log &
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
    depends_on:
      - "postgres_1"