jobID: "0"
taskName: "knn"
taskStatus: READY
taskType: OTPSI
orgDID: computer1
hostname: 192.168.40.230
minioUrl: http://192.168.40.230:32000
minioAccess: minio
minioSecret: minio123

configPath: /opt/OpenHuFu/release/config
image:
  repository: docker.oa.com:5000/mpc/openhufu-server
  tag: "6.0"
  pullPolicy: IfNotPresent
key: node-role.kubernetes.io/mpc
values: mpc
app: mpc-chart
# namespace is the values for deploy namespace
namespace: mpc
# service.type is the values for service type
service:
  type: NodePort
  # service port
  port: 12345
  # container port
  targetPort: 12345
  # k8s port
  nodePort: 31050
