version: '3.3'

services:
  tpch_party1:
    image: maven:3.8-openjdk-11
    container_name: tpch_party1
    working_dir: /usr/src/mymvn
    restart: "no"
    command: nohup java -jar ./bin/onedb_owner_server.jar -c ./config/server1.json > ./log/tpch_party1.log &
    environment:
      - ONEDB_ROOT=/usr/src/mymvn
    volumes:
      - $PWD/../../../release/bin:/usr/src/mymvn/bin
      - $PWD/../../../release/adapter:/usr/src/mymvn/adapter
      - $PWD/config:/usr/src/mymvn/config
      - $PWD/log:/usr/src/mymvn/log
      - $PWD/cert:/usr/src/mymvn/cert
    networks:
      - owner_tpch_1
      - public_tpch
    ports:
      - 12101:12345

  tpch_party2:
    image: maven:3.8-openjdk-11
    container_name: tpch_party2
    working_dir: /usr/src/mymvn
    restart: "no"
    command: nohup java -jar ./bin/onedb_owner_server.jar -c ./config/server2.json > ./log/tpch_party2.log &
    environment:
      - ONEDB_ROOT=/usr/src/mymvn
    volumes:
      - $PWD/../../../release/bin:/usr/src/mymvn/bin
      - $PWD/../../../release/adapter:/usr/src/mymvn/adapter
      - $PWD/config:/usr/src/mymvn/config
      - $PWD/log:/usr/src/mymvn/log
      - $PWD/cert:/usr/src/mymvn/cert
    networks:
      - owner_tpch_2
      - public_tpch
    ports:
      - 12102:12345

  tpch_party3:
    image: maven:3.8-openjdk-11
    container_name: tpch_party3
    working_dir: /usr/src/mymvn
    restart: "no"
    command: nohup java -jar ./bin/onedb_owner_server.jar -c ./config/server3.json > ./log/tpch_party3.log &
    environment:
      - ONEDB_ROOT=/usr/src/mymvn
    volumes:
      - $PWD/../../../release/bin:/usr/src/mymvn/bin
      - $PWD/../../../release/adapter:/usr/src/mymvn/adapter
      - $PWD/config:/usr/src/mymvn/config
      - $PWD/log:/usr/src/mymvn/log
      - $PWD/cert:/usr/src/mymvn/cert
    networks:
      - owner_tpch_3
      - public_tpch
    ports:
      - 12103:12345

networks:
  owner_tpch_1:
    external: true
  owner_tpch_2:
    external: true
  owner_tpch_3:
    external: true
  public_tpch:
    driver: bridge
    name: public_tpch