name: CI Workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Compile ABY4j
      run: cd aby4j && git submodule update --init && export OPENHUFU_ROOT=../ && ./package.sh all && cd ..
    - name: Build with Maven
      run: ./scripts/build/package.sh
    - name: Upload Hu-Fu Release Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: OpenHuFu-release
        path: release
